cargo-features = ["edition2021"]

[package]
name = "logimu"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "*"
serde = { version = "*", features = ["derive"] }
erased-serde = "*"
typetag = "*"

[dev-dependencies]
serde_test = "*"
